Repository TechnologyWithoutBorders/Swift-App, pull requests merged in 2021-01, with the labels that each got.

#21 Added textview to HospitalActivity which displays the amount of devic…
  app/src/main/java/ngo/teog/swift/gui/hospital/HospitalActivity.java
  app/src/main/res/layout/activity_hospital.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, usability

#32 fix missing delivery of hospital ID when creating report
  app/src/main/java/ngo/teog/swift/gui/deviceInfo/DeviceInfoActivity.java
  app/src/main/java/ngo/teog/swift/gui/reportCreation/ReportCreationActivity.java
Labels: bug, urgent

#34 adjust focus order
  app/src/main/res/layout/activity_login.xml
Labels: usability

#46 Maintenance/fix layout warnings
  app/src/main/java/ngo/teog/swift/gui/deviceCreation/NewDeviceActivity2.java
  app/src/main/java/ngo/teog/swift/gui/hospital/HospitalActivity.java
  app/src/main/res/layout/acitivty_image_capture.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_advanced_hospital.xml
  app/src/main/res/layout/activity_device_info.xml
  app/src/main/res/layout/activity_hospital.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_new_device.xml
  app/src/main/res/layout/activity_new_device2.xml
  app/src/main/res/layout/activity_new_device3.xml
  app/src/main/res/layout/activity_report_creation.xml
  app/src/main/res/layout/activity_report_info.xml
  app/src/main/res/layout/activity_user_info.xml
  app/src/main/res/layout/fragment_barcode.xml
  app/src/main/res/layout/header_hospital.xml
  app/src/main/res/layout/row_reports.xml
  app/src/main/res/layout/row_todo.xml
  app/src/main/res/layout/spinner_status.xml
  app/src/main/res/menu/menu_my_hospital.xml
  app/src/main/res/values/strings.xml
Labels: maintenance, performance

#44 replace language specific code section
  app/src/main/java/ngo/teog/swift/gui/deviceCreation/NewDeviceActivity2.java
Labels: bug, maintenance

#42 Fix/share assets
  app/src/main/AndroidManifest.xml
  app/src/main/java/ngo/teog/swift/gui/deviceInfo/DeviceInfoActivity.java
  app/src/main/java/ngo/teog/swift/gui/main/MainActivity.java
  app/src/main/java/ngo/teog/swift/gui/main/MainViewModel.java
  app/src/main/java/ngo/teog/swift/gui/reportInfo/ReportInfoActivity.java
  app/src/main/java/ngo/teog/swift/gui/userInfo/UserInfoActivity.java
  app/src/main/java/ngo/teog/swift/helpers/Defaults.java
  app/src/main/java/ngo/teog/swift/helpers/data/ReportInfo.java
  app/src/main/java/ngo/teog/swift/helpers/data/ViewModelModule.java
  app/src/main/res/menu/menu_report_info.xml
  app/src/main/res/values/strings.xml
Labels: bug, usability

#41 Maintenance/last update export
  app/src/main/java/ngo/teog/swift/gui/hospital/PortationActivity.java
  app/src/main/java/ngo/teog/swift/helpers/Defaults.java
Labels: maintenance

#39 add query for image capture action
  app/src/main/AndroidManifest.xml
Labels: maintenance
