Repository TechnologyWithoutBorders/Swift-App, pull requests merged in 2021-04, with the labels that each got.

#70 Report screen
  app/src/main/java/ngo/teog/swift/gui/reportInfo/ReportInfoActivity.java
  app/src/main/res/drawable/ic_baseline_arrow_right_alt_24.xml
  app/src/main/res/layout/activity_report_info.xml
  app/src/main/res/layout/row_reports.xml
  app/src/main/res/values/strings.xml
Labels: usability

#72 Fix/tutorial
  app/build.gradle
  app/src/main/java/ngo/teog/swift/gui/BaseActivity.java
  app/src/main/java/ngo/teog/swift/gui/deviceInfo/DeviceInfoActivity.java
  app/src/main/java/ngo/teog/swift/gui/hospital/HospitalActivity.java
  app/src/main/java/ngo/teog/swift/gui/reportInfo/ReportInfoActivity.java
  app/src/main/java/ngo/teog/swift/gui/userProfile/UserProfileActivity.java
Labels: bug, usability

#75 Maintenance/remove unused strings
  app/src/main/res/layout/activity_report_info.xml
  app/src/main/res/layout/row_reports.xml
  app/src/main/res/values/strings.xml
Labels: maintenance, text
